### ISSUE TITLE
crear FAQ page

### ISSUE THREAD

**Issue by gaboesquivel** [CostaRicaJS/costaricajs.github.io#11]
- Como organizar un meetup?
- Quienes pueden participar ?
- Tiene algun costo?
- etc

**Comment by stevengpa** [comment]
Gabo, creo que sería bueno crear un repositorio con una aplicación ( cascaron ) en Node quizás para que la comunidad ayude en un lugar centralizado a trabajar he implementar las iniciativas de la comunidad, por ejemplo el FAQ

**Comment by stevengpa** [comment]
También sería bueno como definir patrones y un stack, Functional Programming ó MVC, structura de los folders [ private | public { js ( src & dist ) } ....]

**Comment by gaboesquivel** [comment]
@StevenPerez esa es la idea con este sitio :) .. esta creado con https://hexo.io/,  el código esta en el branch source. Es sencillo.  Puedes empezar ahí, en el wiki hay algo de documentación https://github.com/CostaRicaJS/costaricajs.github.io/wiki ... si consideras que hace falta información te agradezco ayuda con la documentación.

**Comment by stevengpa** [comment]
Perfecto, en cuanto pueda voy a revisar las fuentes ( hexo, branch source ) voy a ir anotando datos del proceso ya que mis primeras dudas fueron:

1) Como hacer un clone del branch source y como se encuentra estructurado? (guía rápida / breve introducción a hexo).
2) Vi que utilizan un software para ver los issues, sin embargo no se utilizarlo, entonces seria otro caso a analizar y documentar.
3) Como funciona slack y como ser parte de costaricajs? (Guía rápida)

No se si algunas de ellas existen :) ... esta es mi visión de cero antes de ver las fuentes a detalle, entonces le confirmo en los próximos días.

**Comment by gaboesquivel** [comment]
1. http://pcottle.github.io/learnGitBranching/
   https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell
   https://guides.github.com/activities/contributing-to-open-source/ 
2. usamos GIT. También podrías la extension hub.github.com pero no es necesario.
3. https://slack.com .. necesitamos implementar esto poder unirse automáticamente sin invitación https://github.com/CostaRicaJS/costaricajs.github.io/issues/10  ... ver ejemplo en http://latamjs.org/
