### ISSUE TITLE
Sobre creación de páginas

### ISSUE THREAD

**Issue by stevengpa** [CostaRicaJS/costaricajs.github.io#16]
Este issue corresponde al caso de la creación de páginas informativas como Acerca, el cual se encuentra pendiente de ingresar bajo el formato standard ( carga del layout, routes => css / js ). 

De momento Acerca se encuentra dentro de la ruta <strong>Themes > costaricajs > source > views > acerca > index.ejs</strong>, sin embargo, no he logrado hacer que dicha página:

<ol> 
<li>Cargue el layout que se encuentra en la ruta <strong>Themes > costaricajs > layout > layout.ejs</strong></li>
<li>Importar en el archivo <strong>Themes > costaricajs > source > views > acerca > index.ejs</strong> el CSS que se encuentra en la ruta <strong>Themes > costaricajs > source > css > acerca.styl</strong></li>
</ol>

<strong>Nota:</strong> Una vez establecidos los pasos y logrado dicho objetivo, estaríamos listos para iniciar la documentación de como aportar al sitio web de CostaRicaJS ! :+1:

**Comment by gaboesquivel** [comment]
usar `hexo new [template] nombre de publicacion`  
Ejemplos `hexo new page faq`,  `hexo new post "programación funcional"`
ver commit https://github.com/CostaRicaJS/costaricajs.github.io/commit/94c27113fcbf0e7e549ff287903b6519eca52782

**Comment by stevengpa** [comment]
ok voy a analizar el efecto del hexo new page para ver si carga el layout, css, etc ... andaba perdido porque estaba mejorando mi librería cooldb-promise pero ya esta lista https://www.npmjs.com/package/cooldb-promise ... voy a hacer un proyecto con esta libreria para asegurame que todo esta bien de acuerdo al testing
