### ISSUE TITLE
Actualizar costaricajs.github.io

### ISSUE THREAD

**Issue by stevengpa** [CostaRicaJS/costaricajs.github.io#17]
<h3>Publicar nueva versión</h3>

<h5>De este:</h5>

![image](https://cloud.githubusercontent.com/assets/10041338/8268895/0bd53154-1750-11e5-8a7d-a8b292cf4041.png)

<h5>A este:</h5>

![image](https://cloud.githubusercontent.com/assets/10041338/8268902/4aca3364-1750-11e5-87f8-b4d541886e13.png)

**Comment by gaboesquivel** [comment]
http://costaricajs.github.io/

**Comment by stevengpa** [comment]
Excelente Gabo !!
