### ISSUE TITLE
necesita mejor diseño

### ISSUE THREAD

**Issue by gaboesquivel** [CostaRicaJS/costaricajs.github.io#23]
el sitio en general necesita un mejor diseño

**Comment by avenidanet** [comment]
Listo, ya estamos trabajando en ello. Mi diseñador lo tengo medio tiempo.
El flyer ya esta listo

**Comment by gaboesquivel** [comment]
Hola @avenidanet  Costa Rica JS is not urgent.  let's do nodeschool site first https://github.com/nodeschool/costarica/issues/5

gracias

**Comment by avenidanet** [comment]
@gaboesquivel Materiales, sitio web y flyer.
Entre hoy y mañana, posteos para Facebook
[Nodeschool.zip](https://github.com/CostaRicaJS/costaricajs.github.io/files/234739/Nodeschool.zip)

**Comment by avenidanet** [comment]
@gaboesquivel Este funciona para posteos
![nodeschool](https://cloud.githubusercontent.com/assets/1860889/14798369/8b6ddbda-0af4-11e6-95a1-e8fb4c7c333e.png)

**Comment by gaboesquivel** [comment]
👍  💯   tks

**Comment by msolano00** [comment]
Hola hola, todavia ocupan ayuda con esto?

**Comment by gaboesquivel** [comment]
si, pero voy a cerrar este y abrir uno nuevo. Porque esto es para el sitio costaricajs.co y se confundio con nodeschool
