### ISSUE TITLE
cambiar plataforma de blogging ?

### ISSUE THREAD

**Issue by gaboesquivel** [CostaRicaJS/costaricajs.github.io#32]
Conversacion original en slack. 

Mhack Redcom
que les parece ese CMS Ghost basado en Node.js para hacer el sitio de la comunidad?

gaboesquivel 
el blog tiene que ser completamente abierto
que todos puedan publicar
en este momento, para publicar solo necesitas hacer un pull request
si usar ghost nos exige cuentas para la gente que escriba
tomando en cuenta que muy poca gente publica articulos…  3 gatos
entonces pues no seria big deal, en realidad

Mhack Redcom 
Si correcto!

Carlos Vega 
La otra cosa es que Ghost esta optimizado para blogging, no tanto para sites. Entonces habria que evaluar que ventajas tendria usar Ghost vs, por ejemplo, Keystone  
O no se si te referis a usar Ghost solo para el blog

Mhack Redcom 
Yo estaba justamente trabajando en ambos casos y vi que puedo crear muchas cosas en Ghost, no toma mucho tiempo, en realidad pensé crear el sitio completo! Pero sigo viendo que tal y les cuento

**Comment by alterx** [comment]
Actualmente se usa Hexo, ¿qué features de Ghost queremos que no tenga Hexo?

¿Hay un roadmap de las cosas que se quieren para el sitio en el futuro?

**Comment by CharliePops** [comment]
Se puede hacer un sitio donde los artículos sean archivos en Markdown, y si alguien quiere publicar algo hace un pull request del archive .md. Es solo una idea, no sé que tanto quieren hacer en el sitio.

**Comment by gaboesquivel** [comment]
@CharliePops  asi funciona actualmente.   el post puede ser markdown o html

**Comment by gaboesquivel** [comment]
no hay un roadmap, pero tenemos varias ideas en  https://github.com/CostaRicaJS/costaricajs.github.io/issues

**Comment by CharliePops** [comment]
Ah ok, sería bueno hacer una lista ;)

**Comment by alterx** [comment]
Muchas de esas features dependen de la plataforma que se quiera usar, sería bueno definir eso primero y luego seguir con el roadmap.

**Comment by gaboesquivel** [comment]
los requerimientos del blog y el sitio web son sencillos
- todos deben poder publicar
- todos deben poder comentar
- soportar un proceso de revision y aprobación
- soportar custom styling and scripting

listo :)

ahora hay otro montón de cosas que se puede hacer, pero lo único fundamental es eso

**Comment by alterx** [comment]
Las opciones son: 
1. [Keystone](http://keystonejs.com/)
2. [Ghost](http://ghost.org/)
3. Quedarnos con [Hexo](https://hexo.io)

**Comment by alterx** [comment]
Viendo como esta la actividad y los contributors en el repo de Ghost, y el API si me parece que se pueden hacer grandes cosas a futuro. Yo mantengo un proyecto de una amiga con Keystone y pese a que es bien chiva si le he visto bastantes limitaciones, una de ellas es que la comunidad es limitada y hay una cantidad cada vez mas grande de issues sin resolver o que tienen mucho tiempo de estar en proceso de resolverse. 

Otra ventaja de Ghost es que soporta archivos .md OOTB, entonces por ahi simplificamos un poco el proceso de migrar los articulos existentes.

**Comment by cinza** [comment]
Yo me apunto tambien :) cuando tenga tareas nada más me dicen

**Comment by gaboesquivel** [comment]
https://www.staticgen.com/  

https://staticsitegenerators.net/

**Comment by CharliePops** [comment]
A mi la verdad me gusta mas la idea de usar generador sencillo y no un CMS, ejemplo: http://antwarjs.github.io/

**Comment by alterx** [comment]
Si, creo que para lo que necesitamos un CMS puede ser overkill. Propongo que pongamos un deadline para elegir, digamos de acá a quince días (5 de setiembre) sino puede que nos quedemos patinando y no se tome la decisión. En ese caso Hexo (que es lo que se utiliza actualmente) podría servirnos bien. 
@CharliePops , nunca he escuchado de ese, ¿cómo se compara con Hexo?

**Comment by CharliePops** [comment]
@alterx es un poco mas simple de entender y configurar(a mi parecer). Igual no tengo problema en usar Hexo o cualquier otro que funcione, pero si un CMS no creo que sea necesario.

Estoy de acuerdo en que se decida pronto para que no quede en solo una idea.

**Comment by marcialca** [comment]
Buenas gente,

Un pequeño aporte por ahi: https://gohugo.io/  parece ser una plataforma estable y muy flexible, super fácil de instalar y permite lo que Gabo, todos pueden publicar y hay un control de versiones de lo que se escribe y hace.

**Comment by msolano00** [comment]
Hola @marcialca, ya comence a trabajar en el update del sitio, si queres pongamonos de acuerdo por slack, te parece?

**Comment by jgatjens** [comment]
Majes y porque no utilizan https://medium.com para la parte de blogging y asi se pueden enfocar en los otros apsectos que quieren renovar de la pagina.

**Comment by gaboesquivel** [comment]
@jgatjens personalmente no me gustaría medium, porque la mayoría de mis seguidores ahí no hablan español, lo veo más como una plataforma internacional ( inglés ).  Una opinión personal.

@alterx  podríamos correr hosted ghost en AWS. Como funcionaría para que todos puedan publicar y haya un proceso de revisión y aprobación ?  Actualmente eso lo hacemos con un pull request.

Creo que por simplicidad es mejor seguir con hexo, que esta funcionando bien. Así ahorramos tiempo también. A menos que se exponga aquí claramente razones por las cuales otra opción es mejor y vale la pena hacer el cambio.

**Comment by jgatjens** [comment]
@gaboesquivel ok.

**Comment by alterx** [comment]
@gaboesquivel yo me inclino por seguir breteando con hexo, con Medium creo que si hay audiencia en español pero si hay más en inglés. El proceso de aprobación con Ghost es más editorial, uno tiene usuarios (que hay que registrar) y hay distintos roles.

**Comment by gaboesquivel** [comment]
seguimos con Hexo, no cambiaremos la plataforma. Al menos por ahora.
